const MISSING_FIELD = 'REQUIRED FIELD MISSING';
const EXISTED_USER = 'THIS USER ALREADY EXISTED';
const WRONG_FORMAT = 'SOME FIELDS ARE IN WRONG FORMAT';

module.exports = {
  MISSING_FIELD,
  EXISTED_USER,
  WRONG_FORMAT
};